apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ .Release.Name }}-developer-manager
rules:
- apiGroups: [""]
  resources: ["deployments", "pods", "services", "endpoints", "jobs", "nodes", "secrets", "configmaps"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]